name: Scheduler

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [master]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - name: Update sponsors
        run: npm run generate
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: YunYouJun
          AFDIAN_API_TOKEN: ${{ secrets.AFDIAN_API_TOKEN }}
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: 'chore: update sponsors.svg'
          add: 'public/sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
